# Generated by Django 6.0.2 on 2026-02-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(max_length=1024, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='CISA', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['link'], name='feeds_artic_link_f1249d_idx')],
            },
        ),
    ]
