# Generated by Django 6.0.2 on 2026-02-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source'], name='feeds_artic_source_1a1a61_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_date'], name='feeds_artic_publish_e3d77c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source', 'published_date'], name='feeds_artic_source_566f32_idx'),
        ),
    ]
