# Generated by Django 6.0.2 on 2026-02-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_article_feeds_artic_source_1a1a61_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='affected_tech',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='severity',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='threat_type',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['threat_type'], name='feeds_artic_threat__0a1290_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['severity'], name='feeds_artic_severit_554c25_idx'),
        ),
    ]
