# Generated by Django 6.0.2 on 2026-02-16 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_article_affected_tech_article_ai_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=512)),
                ('ioc_type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('md5', 'MD5 Hash'), ('sha1', 'SHA1 Hash'), ('sha256', 'SHA256 Hash'), ('cve', 'CVE Identifier'), ('email', 'Email Address')], db_index=True, max_length=16)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('context', models.TextField(blank=True, default='')),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('articles', models.ManyToManyField(related_name='iocs', to='feeds.article')),
            ],
            options={
                'verbose_name': 'IOC',
                'verbose_name_plural': 'IOCs',
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['ioc_type', 'value'], name='feeds_ioc_ioc_typ_721f13_idx'), models.Index(fields=['ioc_type', 'confidence'], name='feeds_ioc_ioc_typ_9d6861_idx'), models.Index(fields=['first_seen'], name='feeds_ioc_first_s_48888e_idx'), models.Index(fields=['times_seen'], name='feeds_ioc_times_s_b2e328_idx')],
            },
        ),
    ]
